# Generated by Django 5.0.1 on 2024-03-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0002_register_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
