# Generated by Django 5.0.1 on 2024-03-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0004_appoinment_design_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appoinment',
        ),
        migrations.DeleteModel(
            name='design',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.AddField(
            model_name='booking',
            name='event',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='other',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
