# Generated by Django 5.0.1 on 2024-03-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0005_delete_appoinment_delete_design_delete_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('img', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
