# Generated by Django 5.0.1 on 2024-03-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0007_appoinment'),
    ]

    operations = [
        migrations.CreateModel(
            name='design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('your_photo', models.ImageField(null=True, upload_to='media')),
                ('model_photo', models.ImageField(null=True, upload_to='media')),
                ('explain', models.CharField(max_length=100)),
            ],
        ),
    ]
