# Generated by Django 5.0.1 on 2024-03-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0008_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='addframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('photo', models.ImageField(null=True, upload_to='media')),
                ('price', models.IntegerField()),
                ('no_photo', models.CharField(max_length=100)),
            ],
        ),
    ]
