# Generated by Django 5.0.1 on 2024-03-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0009_addframe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addframe',
            old_name='fname',
            new_name='frame_name',
        ),
        migrations.RenameField(
            model_name='addframe',
            old_name='photo',
            new_name='frame_photo',
        ),
        migrations.AlterField(
            model_name='addframe',
            name='no_photo',
            field=models.IntegerField(),
        ),
    ]
