# Generated by Django 5.0.1 on 2024-03-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0013_frame_design_delete_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('event', models.CharField(max_length=10, null=True)),
                ('other', models.CharField(max_length=10, null=True)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20, null=True)),
                ('message', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='booking',
        ),
        migrations.AlterField(
            model_name='frame_design',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
