# Generated by Django 5.0.1 on 2024-03-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0014_event_booking_delete_booking_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event_booking',
            new_name='events_booking',
        ),
    ]
