# Generated by Django 5.0.1 on 2024-03-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0015_rename_event_booking_events_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinments',
            name='message',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
