# Generated by Django 5.0.1 on 2024-03-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0016_appoinments_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame_design',
            name='message',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
