# Generated by Django 5.0.1 on 2024-03-25 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0017_frame_design_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='no_photo',
        ),
    ]
