# Generated by Django 5.0.1 on 2024-03-25 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0019_add_cart_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_f',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('img', models.ImageField(null=True, upload_to='media')),
                ('frame_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio_app.addframe')),
            ],
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
