# Generated by Django 5.0.1 on 2024-03-25 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0020_order_f_delete_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='add_to_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_photo', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(default=0)),
                ('frame_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio_app.addframe')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='add_cart',
        ),
    ]
