# Generated by Django 5.0.1 on 2024-03-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0021_add_to_cart_delete_add_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_to_cart',
            name='no_photo',
        ),
        migrations.RemoveField(
            model_name='add_to_cart',
            name='user_details',
        ),
    ]
