# Generated by Django 5.0.1 on 2024-04-07 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0024_cart_item_delete_cartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='events_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('event', models.CharField(max_length=10, null=True)),
                ('other', models.CharField(max_length=10, null=True)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20, null=True)),
                ('message', models.CharField(max_length=20, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='events_booking',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
