# Generated by Django 5.0.1 on 2024-04-07 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0025_events_book_delete_events_booking_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events_book',
            name='User',
        ),
    ]
