# Generated by Django 5.0.1 on 2024-04-07 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0026_remove_events_book_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events_book',
            new_name='events_booking',
        ),
    ]
