# Generated by Django 5.0.1 on 2024-04-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0030_appoinments_user_frame_design_user_order_f_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame_design',
            old_name='user',
            new_name='user_name',
        ),
    ]
