# Generated by Django 5.0.1 on 2024-04-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0033_alter_event_booking_date_alter_event_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame_design',
            name='message',
            field=models.CharField(max_length=20, null=PendingDeprecationWarning),
        ),
    ]
