# Generated by Django 5.0.3 on 2024-04-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0035_alter_appoinments_user_alter_event_booking_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_booking',
            name='user',
        ),
    ]
