# Generated by Django 5.0.3 on 2024-04-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0036_remove_event_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame_design',
            name='user_name',
        ),
    ]
