# Generated by Django 5.0.1 on 2024-05-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0038_appoinment_delete_appoinments'),
    ]

    operations = [
        migrations.CreateModel(
            name='design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('your_photo', models.ImageField(upload_to='media')),
                ('model_photo', models.ImageField(upload_to='media')),
                ('explain', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='frame_design',
        ),
    ]
