# Generated by Django 5.0.1 on 2024-05-01 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0039_design_delete_frame_design'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='des',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('your_photo', models.ImageField(upload_to='media')),
                ('model_photo', models.ImageField(upload_to='media')),
                ('explain', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=20)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='design',
        ),
    ]
