# Generated by Django 5.0.4 on 2024-05-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0042_alter_des_your_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=20)),
                ('replay', models.CharField(max_length=20)),
            ],
        ),
    ]
