# Generated by Django 5.0.4 on 2024-05-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0043_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='replay',
        ),
    ]
