# Generated by Django 5.0.1 on 2024-05-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0045_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('event', models.CharField(max_length=10, null=True)),
                ('other', models.CharField(max_length=10, null=True)),
                ('date', models.CharField(max_length=30, null=True)),
                ('time', models.CharField(max_length=30, null=True)),
                ('place', models.CharField(max_length=10, null=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=20, null=True)),
                ('message', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='event_booking',
        ),
    ]
