# Generated by Django 5.0.1 on 2024-05-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0048_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='model_photo',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='design',
            name='your_photo',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
