# Generated by Django 5.0.1 on 2024-05-16 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0049_alter_design_model_photo_alter_design_your_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='model_photo',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='your_photo',
            new_name='your',
        ),
    ]
