# Generated by Django 5.0.1 on 2024-05-16 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0050_rename_model_photo_design_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame_order',
            name='status',
        ),
    ]
