# Generated by Django 5.0.1 on 2024-05-19 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0051_remove_frame_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('event', models.CharField(max_length=10, null=True)),
                ('other', models.CharField(max_length=10, null=True)),
                ('date', models.CharField(max_length=30, null=True)),
                ('time', models.CharField(max_length=30, null=True)),
                ('place', models.CharField(max_length=10, null=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=20, null=True)),
                ('message', models.CharField(max_length=20, null=True)),
                ('payment_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='designs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('your', models.FileField(null=True, upload_to='media')),
                ('model', models.ImageField(null=True, upload_to='media')),
                ('explain', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=20)),
                ('payment_status', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='frame_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('img', models.ImageField(upload_to='media')),
                ('message', models.CharField(max_length=20)),
                ('payment_status', models.CharField(max_length=20)),
                ('frame_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio_app.addframe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='booking',
        ),
        migrations.RemoveField(
            model_name='frame_order',
            name='frame_name',
        ),
        migrations.RemoveField(
            model_name='frame_order',
            name='user',
        ),
        migrations.DeleteModel(
            name='design',
        ),
        migrations.DeleteModel(
            name='frame_order',
        ),
    ]
