# Generated by Django 5.0.1 on 2024-05-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_app', '0052_bookings_designs_frame_orders_delete_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='payment_status',
            field=models.CharField(default='not paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='designs',
            name='payment_status',
            field=models.CharField(default='not paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='frame_orders',
            name='payment_status',
            field=models.CharField(default='not paid', max_length=20),
        ),
    ]
